use actix_web::{get, http::StatusCode, post, web, App, HttpResponse, HttpServer, Responder};
use ethers::core::types::{Address, U256};
use ethers::types::Bytes;
use ethers::{
    core::k256::ecdsa::SigningKey,
    signers::{LocalWallet, Signer, Wallet},
};
use kalypso_helper::response::response;
use serde::{Deserialize, Serialize};
use serde_json::json;
use serde_json::Value;
use std::fs;
use std::fs::File;
use std::io::Write;
use std::io::{Error, ErrorKind};
use std::process::{Command, Stdio};
use std::sync::Arc;
use tokio::sync::Mutex;

#[derive(Debug, Serialize)]
struct JsonResponse {
    message: String,
    data: Bytes,
}

#[derive(Debug, Deserialize)]
pub struct Config {
    toml_path: String,
    output_path: String,
}

#[get("/test")]
async fn test() -> impl Responder {
    response(
        "The Noir prover is running!!",
        StatusCode::OK,
        Some("Noir Prover is running!".into()),
    )
}

#[get("/benchmark")]
async fn benchmark() -> impl Responder {
    return HttpResponse::Ok().json(kalypso_generator_models::models::BenchmarkResponse {
        data: "Success".to_string(),
        time_in_ms: 1,
    });
}

#[post("/generateProof")]
async fn generate_proof(
    inputs: web::Json<kalypso_generator_models::models::InputPayload>,
    config: web::Data<Arc<Mutex<Config>>>,
    lock: web::Data<Arc<Mutex<()>>>,
) -> impl Responder {
    let config = config.lock().await;
    let _lock = lock.lock().await; // Acquire lock

    // Write private inputs to askId.toml
    if let Err(err) = write_private_inputs_to_toml(inputs.0.clone(), &config.toml_path) {
        return HttpResponse::InternalServerError().json(JsonResponse {
            message: format!("Failed to write private inputs to TOML file: {:?}", err),
            data: Bytes::new(),
        });
    }

    // Generate proof using external command nargo prove
    let proof_path =
        execute_prove_command(inputs.0.clone(), &config.toml_path, &config.output_path).await;

    match proof_path {
        Ok(file_path) => {
            // Read the output file generated by nargo prove
            match read_output_file(&file_path) {
                Ok(file_contents) => {
                    // Convert the file contents to Bytes
                    let file_bytes = Bytes::from(file_contents);
                    // Generate signed proof asynchronously
                    match get_signed_proof(inputs.0.clone(), file_bytes).await {
                        Ok(proof_data) => {
                            // Construct JSON response with proof data
                            return HttpResponse::Ok().json(
                                kalypso_generator_models::models::GenerateProofResponse {
                                    proof: proof_data.to_vec(),
                                },
                            );
                        }
                        Err(err) => HttpResponse::InternalServerError().json(JsonResponse {
                            message: format!("Failed to generate signed proof: {}", err),
                            data: Bytes::new(),
                        }),
                    }
                }
                Err(err) => {
                    println!("{}", err);
                    HttpResponse::InternalServerError().json(JsonResponse {
                        message: format!(
                            "Failed to read output file: {:?} for file {:?}",
                            err, file_path
                        ),
                        data: get_signed_proof_for_invalid_inputs(inputs.0.clone())
                            .await
                            .expect("Failed generating signature for invalid inputs"),
                    })
                }
            }
        }
        Err(err) => {
            println!("{}", err);
            HttpResponse::InternalServerError().json(JsonResponse {
                message: format!("Failed to generate proof: {:?}", err),
                data: get_signed_proof_for_invalid_inputs(inputs.0)
                    .await
                    .expect("Failed generating signature for invalid inputs"),
            })
        }
    }
}

#[post("/checkInput")]
async fn check_input_handler(
    payload: web::Json<kalypso_generator_models::models::InputPayload>,
) -> impl Responder {
    return HttpResponse::Ok().json(kalypso_ivs_models::models::CheckInputResponse { valid: true });
}

#[post("/verifyInputsAndProof")]
async fn verify_inputs_and_proof(
    payload: web::Json<kalypso_ivs_models::models::VerifyInputsAndProof>,
) -> impl Responder {
    let default_response = kalypso_ivs_models::models::VerifyInputAndProofResponse {
        is_input_and_proof_valid: true,
    };
    return HttpResponse::Ok().json(default_response);
}

// Routes
pub fn routes(conf: &mut web::ServiceConfig) {
    let scope = web::scope("/api")
        .service(test)
        .service(benchmark)
        .service(generate_proof)
        .service(check_input_handler)
        .service(verify_inputs_and_proof);
    conf.service(scope);
}

// Utilites
async fn get_signed_proof_for_invalid_inputs(
    inputs: kalypso_generator_models::models::InputPayload,
) -> Result<Bytes, Box<dyn std::error::Error>> {
    let read_secp_private_key = fs::read("./app/secp.sec").expect("/app/secp.sec file not found");
    let secp_private_key = secp256k1::SecretKey::from_slice(&read_secp_private_key)
        .expect("Failed reading /app/secp.sec")
        .display_secret()
        .to_string();
    let signer_wallet = secp_private_key
        .parse::<LocalWallet>()
        .expect("Failed Created signer_wallet");

    let prover_data: ethers::types::Bytes = inputs.clone().get_public().into();
    let value = vec![ethers::abi::Token::Bytes(prover_data.to_vec())];

    let encoded = ethers::abi::encode(&value);
    let digest = ethers::utils::keccak256(encoded);

    // Sign the message digest
    let signature = signer_wallet
        .sign_message(ethers::types::H256(digest))
        .await
        .expect("Failed Creating signature get_signed_proof_for_invalid_inputs()");

    Ok(signature.to_vec().into())
}

async fn get_signed_proof(
    inputs: kalypso_generator_models::models::InputPayload,
    proof: Bytes,
) -> Result<Bytes, Box<dyn std::error::Error>> {
    // Read the secp256k1 private key from file
    let read_secp_private_key = fs::read("./app/secp.sec").expect("/app/secp.sec file not found");
    let secp_private_key = secp256k1::SecretKey::from_slice(&read_secp_private_key)
        .expect("Failed reading secp_private_key get_signed_proof()")
        .display_secret()
        .to_string();
    let signer_wallet = secp_private_key
        .parse::<LocalWallet>()
        .expect("Failed creating signer_wallet get_signed_proof()");

    // Prepare the data for signing
    // let public_inputs = inputs.ask.prover_data.clone();
    let public_inputs: ethers::types::Bytes = inputs.clone().get_public().into();
    let proof_bytes = proof.clone();
    println!("{:?}", &proof_bytes);

    // Encode the data for signing
    let value = vec![
        ethers::abi::Token::Bytes(public_inputs.to_vec()),
        ethers::abi::Token::Bytes(proof_bytes.to_vec()),
    ];
    let encoded = ethers::abi::encode(&value);
    let digest = ethers::utils::keccak256(encoded);

    // Sign the message digest
    let signature = signer_wallet
        .sign_message(ethers::types::H256(digest))
        .await
        .expect("Failed creating signature get_signed_proof()");

    let sig_bytes: Bytes = signature.to_vec().into();
    // Encode the proof response
    let value = vec![
        ethers::abi::Token::Bytes(public_inputs.to_vec()),
        ethers::abi::Token::Bytes(proof_bytes.to_vec()),
        ethers::abi::Token::Bytes(sig_bytes.to_vec()),
    ];
    let encoded = ethers::abi::encode(&value);
    Ok(encoded.into())
}

fn write_private_inputs_to_toml(
    payload: kalypso_generator_models::models::InputPayload,
    toml_path: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    // let ask_id = inputs.ask_id;
    // println!("{}",payload.get_plain_secrets().unwrap());
    let file_path = format!("{}/{}.toml", toml_path, "temp");

    // Convert Vec<u8> to String
    let json_string = String::from_utf8(payload.get_plain_secrets().unwrap())?;

    // Deserialize JSON string to serde_json::Value
    let json_value: Value = serde_json::from_str(&json_string)?;

    // Convert serde_json::Value to a TOML string
    let toml_string = toml::to_string(&json_value)?;

    // Write the TOML string to a file
    let mut file = File::create(file_path)?;
    file.write_all(toml_string.as_bytes())?;

    Ok(())
}

async fn execute_prove_command(
    inputs: kalypso_generator_models::models::InputPayload,
    toml_path: &str,
    output_path: &str,
) -> Result<String, Error> {
    let toml_file_path = format!("{}/{}.toml", toml_path, "temp");

    let witness = "foo";

    let mut cmd = Command::new("nargo");
    cmd.arg("execute")
        .arg("-p")
        .arg(&toml_file_path)
        .arg(&witness)
        .current_dir(toml_path)
        .stdout(Stdio::piped())
        .stderr(Stdio::piped());

    // // Execute the command asynchronously
    let output = cmd.output()?;
    // Check if the command was successful
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(Error::new(
            ErrorKind::Other,
            format!("Command failed: {}", stderr),
        ));
    }
    // bb prove -b ./target/hello_world.json -w ./target/witness-name.gz -o ./target/proof
    let output_file_path = output_path.to_string();
    let json_file_path = format!("{}/target/hello_world.json", toml_path);
    let witness_file_path = format!("{}/target/{}.gz", toml_path, witness);
    let mut cmd_bb = Command::new("bb");
    cmd_bb
        .arg("prove")
        .arg("-b")
        .arg(&json_file_path)
        .arg("-w")
        .arg(&witness_file_path)
        .arg("-o")
        .arg(&output_file_path)
        .current_dir(toml_path)
        .stdout(Stdio::piped())
        .stderr(Stdio::piped());

    // Execute the command asynchronously
    let output_bb = cmd_bb.output()?;
    // Check if the command was successful
    if !output_bb.status.success() {
        let stderr = String::from_utf8_lossy(&output_bb.stderr);
        return Err(Error::new(
            ErrorKind::Other,
            format!("Command failed: {}", stderr),
        ));
    }

    Ok(output_file_path)
}

fn read_output_file(file_path: &str) -> Result<Vec<u8>, std::io::Error> {
    fs::read(file_path)
}
